from django.urls import path

from planner.views import (
    about,
    apply_plan,
    cannon_toggle,
    collection,
    collection_bulk,
    collection_export,
    collection_import,
    collection_toggle,
    evolve_toggle,
    find_plan,
    materials,
    normal_capsules,
    normal_plan,
    normal_seek_start,
    normal_tracks,
    picker_past,
    planner,
    seed_backtrack,
    seed_finder,
    seek_pool,
    seek_start,
    seek_status,
    set_region,
    talent_toggle,
    tier_list,
    tracks,
    unit_forms,
    unit_info,
)

urlpatterns = [
    path("", planner, name="planner"),
    path("picker/past/", picker_past, name="picker_past"),
    path("tracks/", tracks, name="tracks"),
    path("seed/backtrack/", seed_backtrack, name="seed_backtrack"),
    path("seek/", seed_finder, name="seed_finder"),
    path("seek/pool/", seek_pool, name="seek_pool"),
    path("seek/start/", seek_start, name="seek_start"),
    path("seek/status/", seek_status, name="seek_status"),
    path("normal/", normal_capsules, name="normal_capsules"),
    path("normal/tracks/", normal_tracks, name="normal_tracks"),
    path("normal/plan/", normal_plan, name="normal_plan"),
    path("normal/seek/start/", normal_seek_start, name="normal_seek_start"),
    path("plan/", find_plan, name="find_plan"),
    path("apply/", apply_plan, name="apply_plan"),
    path("unit/info/", unit_info, name="unit_info"),
    path("unit/forms/", unit_forms, name="unit_forms"),
    path("collection/", collection, name="collection"),
    path("materials/", materials, name="materials"),
    path("materials/evolve/", evolve_toggle, name="evolve_toggle"),
    path("materials/talent/", talent_toggle, name="talent_toggle"),
    path("materials/cannon/", cannon_toggle, name="cannon_toggle"),
    path("tiers/", tier_list, name="tier_list"),
    path("tiers/<slug:category>/<slug:name>/", tier_list, name="tier_list_page"),
    path("about/", about, name="about"),
    path("region/", set_region, name="set_region"),
    path("collection/toggle/", collection_toggle, name="collection_toggle"),
    path("collection/bulk/", collection_bulk, name="collection_bulk"),
    path("collection/export/", collection_export, name="collection_export"),
    path("collection/import/", collection_import, name="collection_import"),
]
