# Generated by Django 6.0.6 on 2026-06-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_banner_cat_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
