# Generated by Django 6.0.6 on 2026-06-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_banner_end_banner_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('rarity', models.CharField(blank=True, max_length=20)),
                ('forms', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['unit_id'],
            },
        ),
    ]
