# Generated by Django 6.0.6 on 2026-06-30 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cats', to='planner.unit'),
        ),
    ]
