# Generated by Django 6.0.6 on 2026-06-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_link_cats_to_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='canonical',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='owned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='wanted',
            field=models.BooleanField(default=False),
        ),
    ]
