# Generated by Django 6.0.6 on 2026-06-30 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_move_ownership_to_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='owned',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='wanted',
        ),
    ]
