# Generated by Django 6.0.6 on 2026-07-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_remove_cat_owned_remove_cat_wanted'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='set_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
