# Generated by Django 6.0.6 on 2026-07-24 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_unit_set_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolvePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf', models.BooleanField(default=False)),
                ('uf', models.BooleanField(default=False)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evolve_plan', to='planner.unit')),
            ],
        ),
        migrations.CreateModel(
            name='TalentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_plans', to='planner.unit')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('unit', 'slot'), name='unique_talent_plan_slot')],
            },
        ),
    ]
