# Generated by Django 6.0.7 on 2026-07-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_evolveplan_talentplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CannonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cannon_id', models.PositiveSmallIntegerField(unique=True)),
                ('cannon_now', models.PositiveSmallIntegerField(default=0)),
                ('cannon_goal', models.PositiveSmallIntegerField(default=0)),
                ('base_now', models.PositiveSmallIntegerField(default=0)),
                ('base_goal', models.PositiveSmallIntegerField(default=0)),
                ('deco_now', models.PositiveSmallIntegerField(default=0)),
                ('deco_goal', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
