# Generated by Django 6.0.6 on 2026-07-25 10:14

import django.db.models.manager
import neko.region
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_cannonplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='en', max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'base_manager_name': 'all_regions', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='cannonplan',
            options={'base_manager_name': 'all_regions'},
        ),
        migrations.AlterModelOptions(
            name='cat',
            options={'base_manager_name': 'all_regions', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='evolveplan',
            options={'base_manager_name': 'all_regions'},
        ),
        migrations.AlterModelOptions(
            name='talentplan',
            options={'base_manager_name': 'all_regions'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'base_manager_name': 'all_regions', 'ordering': ['unit_id']},
        ),
        migrations.AlterModelManagers(
            name='banner',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_regions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='cannonplan',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_regions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='cat',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_regions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='evolveplan',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_regions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='talentplan',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_regions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='unit',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_regions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='banner',
            name='region',
            field=models.CharField(default=neko.region.current, max_length=2),
        ),
        migrations.AddField(
            model_name='cannonplan',
            name='region',
            field=models.CharField(default=neko.region.current, max_length=2),
        ),
        migrations.AddField(
            model_name='cat',
            name='region',
            field=models.CharField(default=neko.region.current, max_length=2),
        ),
        migrations.AddField(
            model_name='seed',
            name='region',
            field=models.CharField(default=neko.region.current, max_length=2),
        ),
        migrations.AddField(
            model_name='unit',
            name='region',
            field=models.CharField(default=neko.region.current, max_length=2),
        ),
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cannonplan',
            name='cannon_id',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='banner',
            constraint=models.UniqueConstraint(fields=('region', 'name'), name='unique_banner_per_region'),
        ),
        migrations.AddConstraint(
            model_name='cannonplan',
            constraint=models.UniqueConstraint(fields=('region', 'cannon_id'), name='unique_cannon_per_region'),
        ),
        migrations.AddConstraint(
            model_name='cat',
            constraint=models.UniqueConstraint(fields=('region', 'name'), name='unique_cat_per_region'),
        ),
        migrations.AddConstraint(
            model_name='seed',
            constraint=models.UniqueConstraint(fields=('region',), name='unique_seed_per_region'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('region', 'unit_id'), name='unique_unit_per_region'),
        ),
    ]
