# Generated by Django 6.0.7 on 2026-10-08 15:03

import django.db.models.deletion
import planner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_cannonplan_addons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=planner.models._new_key, max_length=43, unique=True)),
                ('region', models.CharField(default='en', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owned', models.ManyToManyField(blank=True, related_name='owned_by', to='planner.unit')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('wanted', models.ManyToManyField(blank=True, related_name='wanted_by', to='planner.unit')),
            ],
        ),
        migrations.AddField(
            model_name='cannonplan',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cannon_plans', to='planner.profile'),
        ),
        migrations.AddField(
            model_name='seed',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seeds', to='planner.profile'),
        ),
        migrations.AddField(
            model_name='talentplan',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talent_plans', to='planner.profile'),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_plans', to='planner.profile'),
        ),
    ]
