# Generated by Django 6.0.7 on 2026-10-08 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0018_move_state_to_profiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.RemoveConstraint(
            model_name='cannonplan',
            name='unique_cannon_per_region',
        ),
        migrations.RemoveConstraint(
            model_name='seed',
            name='unique_seed_per_region',
        ),
        migrations.RemoveConstraint(
            model_name='talentplan',
            name='unique_talent_plan_slot',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='owned',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='wanted',
        ),
        migrations.AlterField(
            model_name='cannonplan',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cannon_plans', to='planner.profile'),
        ),
        migrations.AlterField(
            model_name='seed',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeds', to='planner.profile'),
        ),
        migrations.AlterField(
            model_name='talentplan',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_plans', to='planner.profile'),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_plans', to='planner.profile'),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='planner.unit'),
        ),
        migrations.AddConstraint(
            model_name='cannonplan',
            constraint=models.UniqueConstraint(fields=('profile', 'region', 'cannon_id'), name='unique_cannon_per_region'),
        ),
        migrations.AddConstraint(
            model_name='seed',
            constraint=models.UniqueConstraint(fields=('profile', 'region'), name='unique_seed_per_region'),
        ),
        migrations.AddConstraint(
            model_name='talentplan',
            constraint=models.UniqueConstraint(fields=('profile', 'unit', 'slot'), name='unique_talent_plan_slot'),
        ),
        migrations.AddConstraint(
            model_name='unitplan',
            constraint=models.UniqueConstraint(fields=('profile', 'unit'), name='unique_unit_plan'),
        ),
    ]
