"""
Django settings for nekosite project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Development defaults; a deploy sets DJANGO_DEBUG=0 and supplies the rest from the
# environment. See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set when DEBUG is off.")
    SECRET_KEY = "django-insecure-jxaoc&fydf#a6k(%p(ww0x2q9#%1o52sq^g(&yc(p3g1#rby9("

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "*" if DEBUG else "").split(",")
if render_host := os.environ.get("RENDER_EXTERNAL_HOSTNAME"):
    ALLOWED_HOSTS.append(render_host)
if DEBUG:  # LAN testing from another machine
    CSRF_TRUSTED_ORIGINS = ["http://192.168.0.3:8000", "http://192.168.0.3"]
else:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 365 * 24 * 60 * 60
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # With DEBUG off Django logs request errors only to mail_admins; send them to stderr.
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "handlers": {"console": {"class": "logging.StreamHandler"}},
        "root": {"handlers": ["console"], "level": "WARNING"},
    }


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",  # intcomma, for the resources page's grind counts
    "planner",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # ahead of gzip: static files come precompressed
    "django.middleware.gzip.GZipMiddleware",  # the picker/collection pages are large and repetitive
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "planner.middleware.profile_scope",  # the visitor's own state, and its game version
]

ROOT_URLCONF = "nekosite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "planner.context_processors.region",
                "planner.context_processors.icons",
                "planner.context_processors.tools",
            ],
        },
    },
]

WSGI_APPLICATION = "nekosite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# SQLite locally; a deploy points DATABASE_URL at Postgres.
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}", conn_max_age=600, conn_health_checks=True
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
        if DEBUG
        else "whitenoise.storage.CompressedManifestStaticFilesStorage"
    },
}
# Dev and tests have no collectstatic output; look files up per request instead.
WHITENOISE_AUTOREFRESH = DEBUG

LOGIN_REDIRECT_URL = LOGOUT_REDIRECT_URL = "planner"

# Where a cat icon's "<unit id>/<form>.png" hangs off. `fetch_icons` downloads the whole
# set into static/ (gitignored); the moment it has, we serve our own copies and stop
# hotlinking battlecatsinfo. NEKO_ICON_BASE overrides either way.
ICONS_DIR = BASE_DIR / "planner" / "static" / "planner" / "icons" / "u"
ICON_BASE = os.environ.get(
    "NEKO_ICON_BASE",
    "/static/planner/icons/u" if ICONS_DIR.is_dir() else "https://battlecatsinfo.github.io/img/u",
)

# The same arrangement for the grind materials the resources page shows ("<item id>.png").
ITEMS_DIR = BASE_DIR / "planner" / "static" / "planner" / "icons" / "r"
ITEM_BASE = os.environ.get(
    "NEKO_ITEM_BASE",
    "/static/planner/icons/r" if ITEMS_DIR.is_dir() else "https://battlecatsinfo.github.io/img/r",
)
